### ISSUE TITLE
macOS: Upgrading from 0.26 to 0.29 or 0.30.0 results in leftover text not being cleared.

### ISSUE THREAD

**Issue by coolbluewater** [ratatui-org/ratatui#2213]
ratatui 0.29 or 0.30 (possibly slightly different cases on these two versions that trigger the bug)
macos
crossterm backend

Issue: text is not cleared correctly during rendering even after `f.render_widget(Clear, area);` is called, resulting in leftover text, usually in the bottom of the Block when the old text was longer than the new text.

I know that there are issues regarding the behavior of Clear. However, this works fine in the 0.26 version of ratatui, so I don't think it's related.

### Broken in 0.29.0:
Here's the render function of my custom TextPane struct. All it does is to extract the visible set of lines from a large file so that it can scroll efficiently.

```rust
impl TextPane {
    pub fn render(&mut self, f: &mut Frame<'_>, is_focused: bool, area: Rect) {
        f.render_widget(Clear, area);
        let line_idx = self.vscroll_pos as usize;
        let text = get_numbered_lines(&self.content, line_idx, line_idx + 100);
        // convert from ansi color escapes to tui
        let text = ansi_to_tui::IntoText::into_text(&text)
            .unwrap_or(ansi_to_tui::IntoText::into_text(&mut "").unwrap());
        let paragraph = Paragraph::new(text.clone()).style(Style::default()).block(
            Block::default()
                .borders(Borders::ALL)
                .border_style(Style::default().fg(highlight_color(is_focused)))
                .title(self.title.clone())
                .border_type(BorderType::Rounded),
        );
        f.render_widget(paragraph.scroll((0, self.hscroll_pos)), area);
        // save for page up/page down
        self.h = area.height as i32;
    }
}
fn get_numbered_lines(s: &str, l1: usize, l2: usize) -> String {
    let mut result = String::new();
    for (line_num, line) in s.lines().enumerate().take(l2 + 1) {
        if line_num >= l1 {
            result.push_str(&format!("{}  {}", line_num + 1, line));
            if line_num != l2 {
                result.push('\n');
            }
        }
    }
    result
}
```

### Broken in 0.30.0:
A lot changed in ratatui between 0.29.0 and 0.30.0. Looks like a partial fix occured, but the problem still persists in the case of a custom Treeview widget that also uses `f.render_widget(Clear, area);`.

**Comment by coolbluewater** [comment]
Turned out to be a versioning issue on my machine. Closing.

**Comment by coolbluewater** [comment]
Spoke too soon, the issue is in fact valid: . Reopening.

**Comment by orhun** [comment]
Can you share screenshots of this issue?

Also, can you test the latest beta version of Ratatui as well? (`0.30.0-beta`)

**Comment by coolbluewater** [comment]
The issue does not appear to repro on 0.30.0-beta (along with the corresponding ansi-to-tui beta). Thanks. Is there a GitHub issue for this so that I can understand it?

**Comment by coolbluewater** [comment]
Update: the issue did not repro in 0.30.0-beta on that specific widget (a custom text pane), but does repro on another widget (a custom tree view). Both use the same code to clear the area, so am a bit mystified:
```rust
        f.render_widget(Clear, area);
```

Appreciate if anyone can provide pointers to where related changes were made in ratatui so that I can try to investigate this.

**Comment by joshka** [comment]
There are lots of changes between 26 and 29, even more between 29 and 30. If you want to find what broke this (of what fixed it), clone the repo, point your code at the repo version of ratatui, and then use git bisect to work out which commit broke things.

Given that is fixed in 30, I'm less inclined to chase why it's broken in 29.

**Comment by coolbluewater** [comment]
@joshka, it's still present in 0.30.0-beta, I just updated the title and OP to reflect this.

**Comment by SignalWhisperer** [comment]
I'm facing the same issue with a `Paragraph` defined as:
```rust
let logs = Paragraph::new(logs_text)
    .block(Block::default().title(title).borders(Borders::ALL))
    .style(Style::default().fg(Color::White))
    .wrap(Wrap { trim: true })
    .scroll((app.scroll_y, 0));
```
When I scroll it, the text becomes distorted and there are leftover letters. The two images are from the same run where the second one I've scrolled around a bit more to go back to the same scroll value.

I use `fish, version 4.0.2` in `kitty 0.42.2` on `macOS 26.1 (25B78)` using `ratatui 0.29.0`. I'm using the `CrosstermBackend`.

<img width="894" height="717" alt="Image" src="https://github.com/user-attachments/assets/b705e87b-be21-4825-a8b6-8dde8347a4f9" />

<img width="893" height="714" alt="Image" src="https://github.com/user-attachments/assets/8589adde-7bd7-4679-ba23-82d9cea894c8" />

These are from AWS Lambda function logs (each line prefixed by `AWS: `). This is the part shown on screen:
```text
Command response has been sent
2025-11-22T05:37:19.923000+00:00 2025/11/22/[$LATEST]07d40df3b069407aaeb428bb2ed0d375 2025-11-22T05:37:19.923673Z  INFO Lambda runtime invoke{requestId="5de2f882-b6e7-4471-b787-e34fe34f1185" xrayTraceId="Root=1-69214c0e-4bf29b112201fb4c1c4eace1;Parent=7508f3c04e264083;Sampled=0;Lineage=1:a7502755:0"}: Completed quickly
2025-11-22T05:37:19.925000+00:00 2025/11/22/[$LATEST]07d40df3b069407aaeb428bb2ed0d375 END RequestId: 5de2f882-b6e7-4471-b787-e34fe34f1185
2025-11-22T05:37:19.925000+00:00 2025/11/22/[$LATEST]07d40df3b069407aaeb428bb2ed0d375 REPORT RequestId: 5de2f882-b6e7-4471-b787-e34fe34f1185	Duration: 990.80 ms	Billed Duration: 1110 ms	Memory Size: 128 MB	Max Memory Used: 32 MB	Init Duration: 118.93 ms
```

---

Somehow, switching to another tab in my terminal (`kitty`) and back to this one clears some of the issue, but it seems like the `Max Memory Used: 32 MB` is being displayed off screen.

<img width="889" height="716" alt="Image" src="https://github.com/user-attachments/assets/94709af4-0101-412d-8e6a-dfa4a8856406" />

**Comment by SignalWhisperer** [comment]
I downgraded to `ratatui 0.26` and face the same issue. I don't think the issue lives in ratatui.

**Comment by SignalWhisperer** [comment]
No issue when using Termwiz instead of Crossterm.

<img width="891" height="718" alt="Image" src="https://github.com/user-attachments/assets/7b878a15-192e-4482-8d68-4a1180f05c3f" />
